#=============
# Colorscheme
#=============
[[plugins]]
repo = 'chriskempson/base16-vim'

#========
# ddu
#========
#[[plugins]]
#repo = 'Shougo/ddu.nvim'

#========
# Search
#========
[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'

#======
# Util
#======
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-scripts/surround.vim'

[[plugins]] # close quote
repo = 'vim-scripts/AutoClose'

[[plugins]] # close if-end, if-fi, if { }
repo = 'vim-scripts/endwise.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]] # preview Markdown
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]] # light filer
repo = 'justinmk/vim-dirvish'

#=====
# Git
#=====
[[plugins]]
repo = 'tpope/vim-fugitive'

#========
# Golang
#========
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

#======
# Deno
#======
[[plugings]]
repo = 'vim-denops/denops.vim'
